name: openstack4j CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                java: [ '8', '11', '17' ]
        name: Java ${{ matrix.Java }}
        steps:
            - uses: actions/checkout@v3.3.0
            - name: Set up JDK 11
              uses: actions/setup-java@v3
              with:
                  java-version: ${{ matrix.java }}
                  distribution: temurin
            - name: Build with Maven
              run: mvn --batch-mode --update-snapshots install
